### ISSUE TITLE
Schema migration ?

### ISSUE THREAD

**Issue by crubier** [AEB-labs/cruddl#11]
Does Cruddl have that yet ?

**Comment by henkesn** [comment]
Cruddl sits on top of a document database. From a technical point of view, there is no need for a schema migration. It's up to you to decide what to do. In some cases it might be useful to keep the original data e. g. to keep old (micro) services running, in some cases you will want to migrate. And sometimes even a mixture of both. That's why we currently don't provide schema migration out of the box.
