### ISSUE TITLE
Sparse indexing

### ISSUE THREAD

**Issue by kevinsegal** [AEB-labs/cruddl#12]
I'm trying to mark **multiple** fields as @key, but I'm running into a problem with the unique indexing happening on default for fields used as @key.  How might one go about adding/enabling Arango's sparse indexing feature for unique indices?  I'm a little lost looking at the move-up-field-indices-transformer but I think I'm in the right place...?

**Comment by Yogu** [comment]
Using `@key` on multiple fields is currently not intended, because the key is used as *the one* field that is used with `@reference` (see [the docs](https://github.com/AEB-labs/cruddl/blob/master/docs/modelling.md#references)). If you want to create indices spanning multiple fields, you should use the [indices attribute on `@rootEntity`](https://github.com/AEB-labs/cruddl/blob/master/docs/modelling.md#root-entity-index-definition). Maybe this already solves your problem.

Sparse indices are currently not supported, but would be pretty easy to implement

**Comment by Yogu** [comment]
We now also might have a use case for sparse unique indices, and I'm tempted to just implement it as `sparse` property alongside `unique`, but maybe sparse should just be the default for unique indices. According to the SQL standard, a unique index should permit multiple `NULL` values. MySQL, PostgreSQL and Oracle SQL implement it this way, SQL Server is the odd one. Needs more thoughts, also regarding other index properties beside uniqueness.
