### ISSUE TITLE
Establish entity relationships using natural keys

### ISSUE THREAD

**Issue by anderson900** [AEB-labs/cruddl#255]
First of all, thank you so much for creating and maintaining this excellent library!

I'm working in a domain where we have to populate a significant amount of reference data that has "natural" keys, and then relate other entities to that reference data in an ETL-type data ingest tool.

Unless there is a better approach that I'm not understanding, it seems like we have to do a two-step process to build the necessary relationships to entities that have a natural key:
- look up their GQL/Cruddl/ArangoDB `id` (surrogate key), by using the natural key
- use the `id` (surrogate key) when creating the mutation to insert/update the related entity.

Is there any way that we can create the relationship to the reference data entity directly by its natural key instead of the surrogate key?

Example model:

```graphql
type ReferenceEntity @rootEntity(flexSearch: true, flexSearchLanguage: EN) {
  """
  The natural key of the entity
  """
  entityId: String! @key
}

type IngestedEntity @rootEntity {
  referenceEntity: ReferenceEntity @relation
  someOtherField: String!
}
```

The ingest client has to do something like...

Fetch the ID by the natural key

```graphql
query ($filter: ReferenceEntityFilter) {
  allReferenceEntities(filter:$filter) {
    id
  }
}
```
```json
{
  "filter": {
    "entityId": "MyEntityId"
  }
}
```

And then use that `id` in any subsequent mutation.

```graphql
mutation ($input:CreateIngestedEntityInput!) {
  createIngestedEntity(input:$input) {
    id
    referenceEntity {
      id
      entityId
    }
  }
}
```

```json
{
  "input": {
    "someOtherField": "abc",
    "referenceEntity": 1234
  }
}
```

Where instead, it would be fantastic if there was some way that we could express this mutation with the natural key, e.g.

```json
{
  "input": {
    "someOtherField": "abc",
    "referenceEntity": "MyEntityId"
  }
}
```

Thanks in advance for your help!

**Comment by mfusser** [comment]
From how I understand it maybe you want to use "@reference" instead of "@relation" to link your objects.
With references you can the "@key" of an object.
See the documentation for more information: https://github.com/AEB-labs/cruddl/blob/main/docs/modelling.md#references

**Comment by anderson900** [comment]
Thank you, that's a great point, but I think there are two shortcomings
- You lose the back-reference then, which in some of our use cases may be very useful to have
- The `@reference` directive doesn't _seem_ to work for one-to-many relationships, e.g. to continue with the prior example, it doesn't seem like you can do this:

```
referenceEntityIds: [String!]
referenceEntities: [ReferenceEntity!] @reference(keyField: "referenceEntityIds")
```

**Comment by mfusser** [comment]
Yes both your points are correct.
Unfortunately for relations there is currently no way besides the two-step-process with a query and a mutation to accomplish what you are looking for.
It might be something that could be added in the future although I am not sure if there are technical restrictions that prevent that.
Either way such a feature will most likely not be added in the near future.
Sorry about that.

**Comment by anderson900** [comment]
Thanks, @mfusser, I appreciate your time on this issue.

**Comment by Yogu** [comment]
Thanks for your suggestion @anderson900! I remember that we sometimes wished for a feature like this when creating object graphs where the IDs might not even be known. We solved that problem for most of our cases by allowing object structures to be created in one mutation (with `create...` fields). But that only supports trees and not graphs, and it obviously does not solve your problem.

Regarding performance: I don't think it would be a performance problem to allow creating edges by fields other than ID, granted obviously there is an index on the field (which would be the case for `@key`-annotated fields). We already query for the target objects when adding relation edges to check if they exist, see e.g. here:

https://github.com/AEB-labs/cruddl/blob/be04cae372abc8b528349c59769d82627a1afaec/src/schema-generation/utils/relations.ts#L138

and I think we should keep that because it prevents danging edges from being created. (There are definitely some performance improvements we could do around that part btw. now that I look at it).

I'm not quite sure how I would design the API though. The add-edges API is currently very simple, you just provide the ids as string values. If we add more options, we would either need more input fields or some input object type, both might be a bit bulky.

The other issue is, like @mfusser already pointed out, that we currently don't have too much time to spare. I'll create a ticket in our internal ticketing system however with some notes, maybe if we come up with a nice API, we could someday implement this.
