### ISSUE TITLE
Responses being aggressively cached, preventing mutation operations

### ISSUE THREAD

**Issue by robross0606** [AEB-labs/cruddl#92]
I'm seeing unexpected mutation behavior when attempting to use the simple example schema from the README.  I have this in GraphQL playground:
```
mutation {
  createMovie(input: {
    title: "Test"
  }) {
    id
    title
  }
}
```
First execution worked as expected.  Arango shows a new document and the GraphQL response shows the newly generated document ID.

However, attempts to run the same query a second time do NOTHING.  I've refreshed the GraphQL playground and run again.  The server console shows nothing at all.  

Even worse, I removed the original document from the Arango admin and tried again.  This time the Playground responded as if it had created the document, returning the same ID as before.  I then went into Arango and checked.  The document does NOT exist.

Is cruddl attempting to keep some type of in-memory cache that is out of sync with Arango?

**Comment by robross0606** [comment]
Forgot to mention that if I restart the cruddl application, then I can submit the same query again and it works as expected.

Related to this?  https://github.com/prisma/graphql-playground/issues/242

**Comment by robross0606** [comment]
Nope, just tried through Insomnia and same results.  The server responds immediately with the same results as if the response were cached.

**Comment by robross0606** [comment]
I'm seeing identical behavior across multiple different GraphQL client test tools (Insomnia, Playground on multiple browsers, etc.). Since cruddl is all auto-wired I can't figure out where I could even put a breakpoint or control log output to tell what's happening.

If the return value from the mutation operation is not changed, the mutation itself is not performed and a cached response appears in the client.  If you change even one item in the desired response structure, then a new mutation will occur.

I also tried sending a `cache-control` http header which did not help.

**Comment by robross0606** [comment]
The [try it online](https://aeb-labs.github.io/cruddl/) example does not appear to exhibit this issue.  Is the source code for that example available?

**Comment by Yogu** [comment]
I think you experience this bug: https://github.com/AEB-labs/cruddl/issues/82#issuecomment-504747077

It comes from the feature that if you execute one query or mutation with two top-level fields, both of them should be executed in the same ArangoDB query / transaction. I implemented this in a hacky way by using the parsed GraphQL query as cache key and basically wait until no more fields are fetched for this GraphQL query. This however assumes that the query is re-parsed for each request.

I don't really know how to fix this bug while still preserving the described feature. I guess I could disable it by default.

**Comment by robross0606** [comment]
@Yogu, unclear what you mean by "two top-level fields".  I have tried with a query of:
```
mutation {
  createMovie(input: {
    title: "Test"
  }) {
    id
  }
}
```
Unless I'm misunderstanding, I'm not using more than one top-level field in either the input or output.  This does not appear to impact the problem at all.  If nothing in the query changes, the behavior is cached and the mutation does not occur.  Even just changing the response values lets the mutation occur.

**Comment by robross0606** [comment]
Is there a workaround for this?  The demo out on the web does not appear to have this issue, so either it is using an older version that does not have the problem or it has a workaround.  If it is an older version, what version is it using?  Is the demo source available on github?

**Comment by Yogu** [comment]
> Unless I'm misunderstanding, I'm not using more than one top-level field in either the input or output.

The problem you're experiencing occurs regardless of how many fields are queried. I could easily fix this problem by removing the feature I described. That feature is that *if* you query multiple fields, those are processed in the same transaction.

That's why I wrote that we might want to disable this feature by default. It would however mean that you can't do two mutations in one go transactionally.

> Is there a workaround for this?

Yes, that's the comment I linked above (if you use the apollo client):

```typescript
import { ApolloLink, concat, NextLink } from 'apollo-link';

    createLink(schema:GraphQLSchema): ApolloLink {
        const link = new SchemaLink({
            schema
        });

        // cruddl caches on the document node (arguably a bug) - this is to work around it
        const reparsingMiddleware = new ApolloLink((operation, forward: NextLink | undefined) => {
            if (!forward) {
                throw new Error(`reparsingMiddleware needs to be chained`);
            }
            return forward({
                ...operation,
                query: parse(print(operation.query))
            });
        });

        return concat(reparsingMiddleware, link);
    }
```

> The demo out on the web does not appear to have this issue, so either it is using an older version that does not have the problem or it has a workaround.

It does not have the problem because it does not reuse parsed GraphQL documents for subsequent objects. It parses the GraphQL source on each call, thus generating a new document object, and cruddl behaves correctly. Your setup probably reuses the DocumentAST objects (either through Apollo, or through graphql-tag etc.). That's why you need the workaround I posted above.

**Comment by robross0606** [comment]
Apologies since I'm still learning Apollo and GraphQL.  If I'm understanding you correctly, you're suggesting the workaround is implemented on the client side.  If that is true, it isn't a possible solution for us.  We are developing a GraphQL API to be consumed by other clients we may not control.  We cannot leverage workarounds on those clients.  Moreover, I don't believe this workaround would be possible for standard test clients such as Insomnia, Postman or GraphQL Playground.

Could a change be added to CRUDDL to allow this "feature" to be disabled via server-side configuration?

Another suggestion would be to add would be that, even if it is enabled server-side, pay attention to the HTTP Cache-Control header.  That would still require a client-side change, but could at least be done on test clients such as Insomnia and Postman.

**Comment by Yogu** [comment]
Sorry for all the trouble

> If I'm understanding you correctly, you're suggesting the workaround is implemented on the client side. 

No, it's not a client-side fix in the sense of a HTTP client. I thought you might have exactly the same problem as described in #82, where someone used ApolloClient on the server. If you don't do that, then your situation is a bit different.

I just switched from graphql-yoga to apollo-server in cruddl and could reproduce your problem. It occurs because apparently ApolloServer caches the parsing result of the GraphQL query.

It's not a *caching* feature in cruddl I could disable (cruddl has no caching feature). I was talking about he "feature" that one GraphQL query is always translated to one ArangoDB transaction. I don't really want to disable that because it breaks important guarantees.

Instead, I'm going to two things:

- I'll add the optional property `ProjectOptions.getOperationIdentifier`. It allows you to generate a token object that can be used to unique define an operation. If you e.g. know that each request gets executed with a fresh context object, you can just return the context object as "operation identifier".
- If this property is not specified, operationswith only one top-level field will still work out of the box.
- I'll switch from graphql-yoga to ApolloServer in the example and configure it properly to use the context as operation identifier.

I'll release an alpha version of cruddl when I implemented this so you can test.

**Comment by robross0606** [comment]
Thank you so much!  Looking forward to giving it a try.

**Comment by Yogu** [comment]
I just released 1.1.0-alpha.1, you can give it a try :)

**Comment by robross0606** [comment]
So far, looking good!  I am able to submit the same mutation call multiple times and it created new records.  Onward and upward!  🥇

**Comment by Yogu** [comment]
That's great!

If / when you get the error message *Operations with multiple top-level fields are not supported because no operationIdentifier is configured*, you'll need to configure ApolloServer as it's now documented in the [README](https://github.com/AEB-labs/cruddl#usage), especially

- specifying a `context` function (not a constant value), where you can e.g. use the HTTP request as config, or create any context object you like (it's just important that you don't re-use context objects for subsequent requests)

```typescript
const server = new ApolloServer({
    schema,
    context: ({ req }) => req // pass request as context so we have a unique context object for each operation
});
```

- instruct cruddl to use the context object to identify operations:

```typescript
const project = new Project({
  // ...
    getOperationIdentifier: ({context}) => context as object, // each operation is executed with an unique context object
});
```

**Comment by robross0606** [comment]
I already took a look at the updated README and adjusted the `ApolloServer` part of it.  Still trying to understand the `Project` part.

**Comment by Yogu** [comment]
Maybe the documentation for `getOperationIdentifier` helps?

```typescript
    /**
     * Should return a token object that is the same for all field resolves of one operation, but different for each
     * operation call.
     *
     * This callback is required to group field requests of operations that include multiple top-level fields as
     * graphql-js offers no reliable way to group these requests together. Cruddl's transactional guarantees can only
     * be kept if it know which field requests belong to one operation.
     *
     * The result must be an object because it is used in a WeakMap so that query results are cleaned up when the
     * operation is complete.
     *
     * If this is not implemented or the callback returns undefined, operations with more than one top-level fields or
     * operations containing top-level fragment spreads will not be supported.
     */
    readonly getOperationIdentifier?: (params: FieldResolverParameters) => object | undefined
```

If not, I can try to improve the documentation.

**Comment by itsezc** [comment]
@Yogu I seem to have the exact same issue, for a collection of Users, I ran a query for allUsers, then ran createUser mutation (which successfully created the new entry), however when I run allUsers query again it returns an empty array.

I'm using the latest version of Cruddl and Apollo Server, and testing on the GraphQL Playground. I've also made the all the necessary changes noted on the README.

```js
const Project = new ProjectConstructor({
	sources: [
		{
			name: 'schema.graphql',
			body: schema
		},
		{
			name: 'permission-profiles.json',
			body: JSON.stringify({
				permissionProfiles: {
					default: {
						permissions: [
							{
								roles: ['users'],
								access: 'readWrite'
							}
						]
					}
				}
			})
		}
	],
	getExecutionOptions: ({ context }) => ({ authRoles: ['users'] }),
	getOperationIdentifier: ({ context }) => context
})```
